apiVersion: v1
kind: ConfigMap
metadata:
  name: namespace-termination-locker-webhook
data:
  whitelist.json: |
    { 
      "whitelists": [
        {
          "group": "",
          "version": "v1",
          "resource": "configmap",
          "name": "kube-root-ca.crt"
        },
        {
          "group": "",
          "version": "v1",
          "resource": "serviceaccount",
          "name": "default"
        }
      ]
    }